### ISSUE TITLE
Azure Connection in YAML required?

### ISSUE THREAD

**Issue by riezebosch** [WouterDeKort/VSTSHostedAgentPool#2]
https://github.com/WouterDeKort/VSTSHostedAgentPool/blob/a60bf9e73700d2e19b8bf489bef30de3dc0e6716/builds/build.yaml#L9

Where's the azureSubscription used for? Because (AFAICS) all required parameters for executing packer is passed through using parameters/variables.

I see you use the [AzurePowershell](https://github.com/WouterDeKort/VSTSHostedAgentPool/blob/master/builds/build.yaml#L6) task and my question is: why?

Think I found the answer, because now my build fails because I have to login...

**Comment by WouterDeKort** [comment]
Hi @riezebosch,

you're correct in that the Azure PowerShell tasks helps me in logging in to the Azure subscription. Otherwise you would have to add the login code manually to the script. This way, all prerequisites are done by the task and it makes it much easier to run the script.

Kind regards,
Wouter
